language: node_js

node_js:
  - '4'
  - '6'
  - 'stable'

sudo: false

git:
  depth: 10

before_script:
  - yarn global add codecov

script: yarn run test:ci

after_success: codecov

cache:
  yarn: true
  directories:
    - node_modules
